// <auto-generated />
namespace DynamicObjectListing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_session_analysis_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_session_analysis_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202305140635253_adding_session_analysis_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
